# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doublefact <- function(x) {
    .Call(`_NLPwavelet_doublefact`, x)
}

M1_func <- function(r, d, tau1_l, sigmasq) {
    .Call(`_NLPwavelet_M1_func`, r, d, tau1_l, sigmasq)
}

M2_func <- function(r, d, tau1_l, sigmasq) {
    .Call(`_NLPwavelet_M2_func`, r, d, tau1_l, sigmasq)
}

h_func <- function(x, d, nu, tau2_l, sigmasq) {
    .Call(`_NLPwavelet_h_func`, x, d, nu, tau2_l, sigmasq)
}

L_func <- function(x, d, nu, tau2_l, sigmasq) {
    .Call(`_NLPwavelet_L_func`, x, d, nu, tau2_l, sigmasq)
}

L_dd_func <- function(x, nu, tau2_l, sigmasq) {
    .Call(`_NLPwavelet_L_dd_func`, x, nu, tau2_l, sigmasq)
}

Lap_approx <- function(d, nu, tau2_l, sigmasq) {
    .Call(`_NLPwavelet_Lap_approx`, d, nu, tau2_l, sigmasq)
}

lhood_contrib <- function(d, r, nu, M1, gamma1_l, gamma2_l, tau1_l, tau2_l, sigmasq, d_star, sigma_star) {
    .Call(`_NLPwavelet_lhood_contrib`, d, r, nu, M1, gamma1_l, gamma2_l, tau1_l, tau2_l, sigmasq, d_star, sigma_star)
}

post_odds_func <- function(d, r, nu, M1, sigmasq, gamma1_l, gamma2_l, tau1_l, tau2_l, d_star, sigma_star) {
    .Call(`_NLPwavelet_post_odds_func`, d, r, nu, M1, sigmasq, gamma1_l, gamma2_l, tau1_l, tau2_l, d_star, sigma_star)
}

post_mixprobs_func <- function(post_odds) {
    .Call(`_NLPwavelet_post_mixprobs_func`, post_odds)
}

post_odds_func_indiv <- function(method, d, r, M1, sigmasq, gamma_l, tau_l, d_star = NULL, sigma_star = NULL) {
    .Call(`_NLPwavelet_post_odds_func_indiv`, method, d, r, M1, sigmasq, gamma_l, tau_l, d_star, sigma_star)
}

lhood_contrib_indiv <- function(method, d, r, M1, gamma_l, tau_l, sigmasq, d_star = NULL, sigma_star = NULL) {
    .Call(`_NLPwavelet_lhood_contrib_indiv`, method, d, r, M1, gamma_l, tau_l, sigmasq, d_star, sigma_star)
}

